### ISSUE TITLE
Issue in hello_qiskit H gate exercise comment # add a H gate on qubit 0

### ISSUE THREAD

**Issue by AlainChance** [stefan-woerner/qiskit_tutorial#1]
Hello,
In the hello_qiskit, H gate exercise, I suggest correcting the following comment:
`# add a H gate on qubit 0, flipping the qubit from |0> to |1>`
as follows:
`# add a H gate and apply it on qubit 0, mapping |0> to 1/√2(|0⟩+|1⟩)=:|+⟩`
Thanks

**Comment by stefan-woerner** [comment]
corrected, thanks!
